import type { Metadata } from "next";
import "@/app/_styles/globals.css";

import { Josefin_Sans } from "next/font/google";

import Navbar from "@/app/_components/Navbar";
import ReservationProvider from "./_context/ReservationContext";
import { auth } from "./_services/auth/auth";

export const metadata: Metadata = {
  title: "The Wild Oasis",
  description: "Generated by create next app",
};

const josefin = Josefin_Sans({
  subsets: ["latin"],
  display: "swap",
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en">
      <body
        className={`${josefin.className} bg-primary-950 text-primary-100 min-h-screen flex flex-col`}
      >
        <div>
          <Navbar image={session?.user?.image ?? ""} />
        </div>
        <div className="lg:flex-1 lg:px-8 lg:py-8">
          <main className="max-w-7xl mx-auto">
            <ReservationProvider>{children}</ReservationProvider>
          </main>
        </div>
      </body>
    </html>
  );
}
